services:
  - type: web
    name: todo-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 8000
    envVars:
      - key: ENV
        value: PRODUCTION
      - key: LOG_LEVEL
        value: INFO
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 8000
      - key: JWT_SECRET_KEY
        fromDatabase:
          name: todo
          property: password
      - key: DATABASE_URL
        fromDatabase:
          name: todo
          property: connectionString

databases:
  - name: todo
    plan: free
    databaseName: todo_db
    user: todouser
